"""
Single source of truth for the QIA pipeline.

Every script imports `cfg` from here instead of hardcoding paths, thresholds,
or model settings. When you finetune a new segmentation model:

    1. Bump `run_name` (e.g. "segformer_v3") and update `seg_checkpoint_path`.
    2. Re-run the pipeline scripts in order.

Every script's outputs land under output/<run_name>/..., so results from
different segmentation model iterations never overwrite each other and stay
directly comparable.
"""

import os
 
_CPU_THREAD_LIMIT = "2"
os.environ.setdefault("OMP_NUM_THREADS", _CPU_THREAD_LIMIT)
os.environ.setdefault("MKL_NUM_THREADS", _CPU_THREAD_LIMIT)
os.environ.setdefault("OPENBLAS_NUM_THREADS", _CPU_THREAD_LIMIT)
os.environ.setdefault("NUMEXPR_NUM_THREADS", _CPU_THREAD_LIMIT)

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class PipelineConfig:
    # ---- run identity -----------------------------------------------------
    run_name: str = "SegFormer_v3"          # CHANGE THIS per finetuning iteration, v3 = with greyscaling

    # ---- top-level paths ----------------------------------------------------
    data_dir: Path = Path("data")
    output_root: Path = Path("outputs")

    # ---- segmentation model --------------------------------------------------
    seg_checkpoint_path: str = "models/trained_SegFormer_noVal.pt"  # CHANGE THIS per finetuning iteration
    num_seg_classes: int = 3
    class_names: tuple = ("background", "floc", "filament")
    class_colors: dict = field(default_factory=lambda: {
        0: (0, 0, 0),        # background
        1: (255, 0, 0),      # floc - red
        2: (0, 255, 0),      # filament - green
    })

    # ---- thresholds (from your threshold-optimization step; index-aligned
    # with class_names -- background has none since it's the default) --------
    floc_threshold: float = 0.7814933       # CHECK/RE-TUNE per finetuning iteration v3
    filament_threshold: float = 0.6403097   # CHECK/RE-TUNE per finetuning iteration v3

    # ---- tiled inference ------------------------------------------------------
    tile_size: int = 1024
    overlap: int = 64

    # ---- normalization (must match whatever the segmentation model was
    # trained/fine-tuned with) --------------------------------------------------
    norm_mean: tuple = (0.485, 0.456, 0.406)
    norm_std: tuple = (0.229, 0.224, 0.225)

    # ---- device / reproducibility ----------------------------------------------
    gpu_id: int = 1
    num_threads: int = 4
    seed: int = 25

    # ---- QC sample images (handpicked, fixed across all runs) -----------------
    qc_images_dirname: str = "sample_images_QC"
    metrics_eval_subdirname: str = "sample_images_phasecontrast"   # subfolder inside qc_images_dir for script 04

    # ---- full-dataset inference inputs -----------------------------------------
    match_table_path: str = "data/microscopic_match_table_extended.xlsx"
    phase_contrast_classification_path: str = "data/PhaseContrast Classifier/microscopyClassificationsV2_OCR_clean.csv"

    # ---- fixed train/test split ----------
    split_train_sheet: str = "train"
    split_test_sheet: str = "test"
    split_group_col: str = "experiment_id"
    split_label_col: str = "label"
    split_merge_col: str = "image_path"             # join key between the split workbook and metrics.xlsx

    # ---- derived paths (don't edit these directly -- change the pieces above) -
    @property
    def output_dir(self) -> Path:
        """output/<run_name>/ -- everything generated by this run lives here."""
        return self.output_root / self.run_name

    @property
    def qc_images_dir(self) -> Path:
        return self.data_dir / self.qc_images_dirname

    @property
    def qc_visualizations_dir(self) -> Path:
        return self.output_dir / "qc_visualizations"

    @property
    def metrics_eval_images_dir(self) -> Path:
        return self.qc_images_dir / self.metrics_eval_subdirname
 
    @property
    def metrics_eval_visualizations_dir(self) -> Path:
        return self.output_dir / "metrics_eval_visualizations"

    @property
    def masks_dir(self) -> Path:
        return self.output_dir / "masks"

    @property
    def metrics_path(self) -> Path:
        return self.output_dir / "metrics.xlsx"

    @property
    def match_table_with_masks_path(self) -> Path:
        return self.output_dir / "match_table_with_masks.xlsx"


# Import this directly: `from config import cfg`
cfg = PipelineConfig()